### ISSUE TITLE
AccountService.GetAccount always returns previously cached Account object from LocalObjectCache

### ISSUE THREAD

**Issue by herrieman79** [rhenium2/HeliumApi.SDK#1]
Example, Account.Balance is never updated after Account object is previously cached using LocalObjectCache.
This causes Account object properties to remain stale, even after restart of the application.

```
    public static async Task<Account> GetAccount(string accountAddress)
    {
        var cachedAccount =
            Cache.Default.GetOne<Account>(x => x.Address.Equals(accountAddress));
        if (cachedAccount != null)
        {
            return cachedAccount;
        }
```

Expectation is that dynamic properties are updated.

**Comment by rhenium2** [comment]
@hvandrie  By default the Account object is cached for 1 day (24 hours). After that it gets renewed. Do you have a usecase to get fresh account data more than once-a-day?

**Comment by herrieman79** [comment]
I wrote an simple Helium Wallet monitor app, it refreshes the wallet every given user-specified interval.
Would be nice to add an param to the function to force renew instead of returning cached result.

**Comment by rhenium2** [comment]
Thanks for your comment. That makes sense.

So I believe you are using [HeliumApi.SDK](https://github.com/rhenium2/HeliumApi.SDK) directly or are you using MyHeliumCat for that?

**Comment by herrieman79** [comment]
Am using HeliumApi.SDK directly.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rhenium2** [comment]
Transferring this issue to [HeliumApi.SDK](https://github.com/rhenium2/HeliumApi.SDK)

**Comment by rhenium2** [comment]
I am working on a fix for this issue to allow disable caching for certain types

**Comment by herrieman79** [comment]
Thanks, much appreciated.
I was thinking you could add optional parameter to force bypassing cache lookup. So, defaults to cache and parameter allows bypassing cache to get online data. It's just a thought.
________________________________

**Comment by rhenium2** [comment]
@hvandrie HeliumApi.SDK version 1.1.0 release [here](https://www.nuget.org/packages/HeliumApi.SDK/1.1.0)

Thanks for your contribution
